- project/plugins.sbt
Small PR to upgrade artifactory
> Updated Artifactory to 1.2.0

- app/connectors/ArrivalConnector.scala
- app/connectors/BaseConnector.scala
- app/connectors/MessageConnector.scala
- app/controllers/ArrivalMessagesController.scala
- app/controllers/ArrivalMovementController.scala
- app/models/domain/Arrival.scala
- app/models/domain/ArrivalWithMessages.scala
- app/models/response/ResponseArrival.scala
- app/models/response/ResponseArrivalWithMessages.scala
- app/models/response/ResponseMessage.scala
- conf/app.routes
- it/connectors/ArrivalConnectorSpec.scala
- it/connectors/MessageConnectorSpec.scala
- test/controllers/ArrivalMessagesControllerSpec.scala
- test/controllers/ArrivalMovementControllerSpec.scala
Updated the responsearrival models
Added new endpoint
If merged, we can't test this as the backend endpoint still needs to be completed.
> Add GET Specific Arrival Endpoint

- app/controllers/actions/ValidateAcceptJsonHeaderAction.scala
- test/controllers/actions/ValidateAcceptJsonHeaderActionSpec.scala
Reverts hmrc/common-transit-convention-traders#76
> Revert "Test Accept header behaviour"

- app/config/AppConfig.scala
- app/connectors/BaseConnector.scala
- app/connectors/DeparturesConnector.scala
- app/controllers/DeparturesController.scala
- app/controllers/actions/ValidateDepartureDeclarationAction.scala
- app/models/request/XSDFile.scala
- conf/app.routes
- conf/application.conf
- conf/xsd-iconvert/cc015b.xsd
- test/controllers/DeparturesControllerSpec.scala
- test/controllers/actions/ValidateDepartureDeclarationActionSpec.scala
- test/data/TestXml.scala
- test/models/request/XSDFileSpec.scala
This cannot currently be properly tested without the backend APIs
> Added public departure declaration notification

- resources/public/api/conf/1.0/application.raml
In one header, in one instance. Content only fix.
> Changing Arrival Movement to Movement Arrival

- resources/public/api/conf/1.0/application.raml
> Caps pull to PULL

- resources/public/api/conf/1.0/application.raml
Updating GET JSON, example descriptions and correcting application/JSON or XML
> Update GETs, other things

- resources/public/api/conf/1.0/docs/overview.md
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1168)
> CTDA-1168/API specification page fix

- resources/public/api/conf/1.0/docs/overview.md
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1179)
[Subtask](https://jira.tools.tax.service.gov.uk/browse/CTDA-1245)
> Ctda 1179/hyperlink to testing guide

- resources/public/api/conf/1.0/application.raml
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1192)
> CTDA-1192/RAML API Description

- resources/public/api/conf/1.0/docs/overview.md
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1261)
> CTDA-1261/tt-for-ni

- app/connectors/BaseConnector.scala
- app/connectors/DeparturesConnector.scala
- app/connectors/ResponseHeaders.scala
- app/controllers/DeparturesController.scala
- app/models/Box.scala
- app/models/BoxId.scala
- app/models/response/HateaosDeparturePostResponseMessage.scala
- app/utils/ResponseHelper.scala
- build.sbt
- it/connectors/DepartureConnectorSpec.scala
- test/connectors/BaseConnectorSpec.scala
- test/controllers/DeparturesControllerSpec.scala
- test/models/response/HateaosDeparturePostResponseMessageSpec.scala
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1062)
> Ctda 1062/save boxid to departures

- resources/public/api/conf/1.0/docs/overview.md
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1406)
> CTDA-1406/NI-go-live

- app/config/Module.scala
- app/controllers/ArrivalMessagesController.scala
- app/controllers/ArrivalMovementController.scala
- app/controllers/DepartureMessagesController.scala
- app/controllers/DeparturesController.scala
- app/controllers/actions/AnalyseMessageAction.scala
- app/metrics/MetricsKeys.scala
- app/utils/analysis/MessageAnalyser.scala
- test/controllers/actions/AnalyseMessageActionSpec.scala
- test/data/TestXml.scala
- test/utils/analysis/MessageAnalyserSpec.scala
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1226)
> Ctda 1226/log message size and movement stats

- resources/public/api/conf/1.0/application.raml
- resources/public/api/conf/1.0/docs/overview.md
- resources/public/api/conf/1.0/docs/pushPull.md
[Ticket 1](https://jira.tools.tax.service.gov.uk/browse/CTDA-1534)
[Ticket 2](https://jira.tools.tax.service.gov.uk/browse/CTDA-1473)
> Ctda 1534/push pull updates

- app/controllers/actions/EnsureGuaranteeAction.scala
- app/controllers/actions/ValidateArrivalMessageAction.scala
- app/controllers/actions/ValidateArrivalNotificationAction.scala
- app/controllers/actions/ValidateDepartureDeclarationAction.scala
- app/controllers/actions/ValidateDepartureMessageAction.scala
- app/models/response/JsonErrorResponse.scala
- resources/public/api/conf/1.0/application.raml
- test/controllers/actions/ValidateArrivalMessageActionSpec.scala
- test/controllers/actions/ValidateArrivalNotificationActionSpec.scala
- test/controllers/actions/ValidateDepartureDeclarationActionSpec.scala
- test/controllers/actions/ValidateDepartureMessageActionSpec.scala
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1475)
> Ctda 1475/json errors

- resources/public/api/conf/1.0/docs/pushPull.md
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1554)
> CTDA 1554/Push pull requirements

- app/controllers/PushPullNotificationController.scala
- app/models/response/HateoasResponseBox.scala
- resources/public/api/conf/1.0/application.raml
- test/controllers/PushPullNotificationControllerSpec.scala
- test/models/response/HateoasResponseBoxSpec.scala
I've two commits, one with and one without a Hateoas response because it slipped through the next last time. I can revert the Hateoas commit if we want to keep it simple
> Ctda 1600 fix raml

- resources/public/api/conf/1.0/application.raml
Our accept headers become the following:
Content folks, check the wording is okay please!
Dev folks, just want to confirm I've not done anything stupid before we merge, works in the RAML previewer though!
> CTDA-1817: Update Accept header to specify things must be JSON

- app/controllers/DeparturesController.scala
- app/controllers/VersionSwitch.scala
- resources/public/api/definition.json
- test/controllers/DeparturesControllerSpec.scala
- test/controllers/VersionSwitchSpec.scala
Route departure POST request according to accept header
> CTCP-182: Submit a Departure Declaration XML

- resources/public/api/conf/2.0/application.raml
- resources/public/api/conf/2.0/docs/errors.md
Needs looking over by the content team.
> CTCP-278: Update RAML to include 413 errors

- resources/public/api/conf/2.0/application.raml
Align 404 description with displayName
> Optimise CTC Traders API v2 endpoint display names

- resources/public/api/conf/1.0/application.raml
> Optimise CTC Traders API v1 response descriptions

- app/routing/ArrivalsRouter.scala
- app/routing/DeparturesRouter.scala
- app/v2/controllers/V2ArrivalsController.scala
- app/v2/controllers/V2DeparturesController.scala
- app/v2/controllers/actions/providers/AcceptHeaderActionProvider.scala
- app/v2/controllers/stream/StreamingParsers.scala
- app/v2/utils/PreMaterialisedFutureProvider.scala
- app/v2/utils/StreamWithFile.scala
- it/connectors/ArrivalMessageConnectorSpec.scala
- test/routing/ArrivalsRouterSpec.scala
- test/routing/DeparturesRouterSpec.scala
- test/routing/VersionedRoutingSpec.scala
- test/v2/controllers/V2ArrivalsControllerSpec.scala
- test/v2/controllers/V2DeparturesControllerSpec.scala
- test/v2/controllers/actions/AcceptHeaderActionSpec.scala
- test/v2/controllers/stream/StreamingParsersSpec.scala
- test/v2/fakes/controllers/FakeV2ArrivalsController.scala
- test/v2/fakes/controllers/FakeV2DeparturesController.scala
- test/v2/fakes/utils/FakePreMaterialisedFutureProvider.scala
- test/v2/utils/PreMaterialisedFutureProviderSpec.scala
- test/v2/utils/StreamWithFileSpec.scala
Using this for testing on staging, but I think this is something we should do anyway. Tests to follow.
> CTCP 1545 - Delay requests until temporary files are completely written

- app/v2/controllers/V2ArrivalsController.scala
- app/v2/services/ValidationService.scala
- test/v2/controllers/V2ArrivalsControllerSpec.scala
The changes are dependent on https://jira.tools.tax.service.gov.uk/browse/CTCP-1724
> [CTCP-1740] attach arrival message for json

- app/metrics/MetricsKeys.scala
- app/v2/connectors/PushNotificationsConnector.scala
- app/v2/connectors/V2BaseConnector.scala
- app/v2/controllers/V2ArrivalsController.scala
- app/v2/controllers/V2DeparturesController.scala
- app/v2/models/errors/PushNotificationError.scala
- app/v2/services/PushNotificationsService.scala
- app/v2/services/XmlMessageParsingService.scala
- it/v2/connectors/PushNotificationsConnectorSpec.scala
- test/v2/controllers/V2ArrivalsControllerSpec.scala
- test/v2/controllers/V2DeparturesControllerSpec.scala
- test/v2/services/PushNotificationServiceSpec.scala
* Updated controller code to remove duplication
Not yet tested with https://github.com/hmrc/transit-movements-push-notifications/pull/9 -- doing that before I undraft
> CTCP-1803: Call push notification service to update timestamps when attaching a new message

- app/v2/controllers/ErrorTranslator.scala
- app/v2/models/errors/FailedToValidateError.scala
- app/v2/services/ValidationService.scala
- test/v2/controllers/ErrorTranslatorSpec.scala
- test/v2/services/ValidationServiceSpec.scala
Counterpart to https://github.com/hmrc/transit-movements-validator/pull/29. Will test once https://github.com/hmrc/common-transit-convention-traders/pull/352 is out of the way.
> CTCP-1466: Fix getting incorrect message when Json can't be parsed.

- resources/public/api/conf/2.0/application.raml
To be reinstated and reworded later.
> CTCP-1751: Remove references to PPNS boxes for now, to be re-added once we can use PPNS

- resources/public/api/conf/2.0/application.raml
Not for merging until we've gotten our PPNS integration up and running.
> CTCP-2138: Mention PPNS in the API defintion

- resources/public/api/conf/2.0/application.yaml
Version 2 accept header API definition
> CTCP-2355-Version2 accept header API definition

- app/v2/connectors/ValidationConnector.scala
- app/v2/models/responses/ValidationResponse.scala
- app/v2/services/ValidationService.scala
- it/v2/connectors/ValidationConnectorSpec.scala
- test/v2/models/ValidationResponseSpec.scala
- test/v2/services/ValidationServiceSpec.scala
Need to add a couple more tests for the new models
> CTCP-3110: Fix business validation errors

- app/v2/controllers/V2MovementsController.scala
- app/v2/models/request/PushNotificationsAssociation.scala
- app/v2/services/PushNotificationsService.scala
- it/v2/connectors/PushNotificationsConnectorSpec.scala
- it/v2/utils/CommonGenerators.scala
- test/v2/controllers/ConvertErrorSpec.scala
- test/v2/controllers/V2MovementsControllerSpec.scala
- test/v2/services/PushNotificationServiceSpec.scala
Must go in with https://github.com/hmrc/transit-movements-push-notifications/pull/20
> CTCP-3684: Pass enrollment EORI to our push notification service
