hmrc/common-transit-convention-traders

app/controllers/ArrivalsController.scala
app/controllers/LocationHeader.scala
test/controllers/ArrivalsControllerSpec.scala

Changed response headers to match /arrivals/{arrivalId} expectation. Simplified LocationHeader to be less prone to issues and to match new location headers received.
Built to work against this stub branch : https://github.com/hmrc/transit-movements-trader-at-destination-stub/tree/CTDA-83-message-addition

Updated Location Headers returned to only send the arrival id

---

app/connectors/ArrivalConnector.scala
app/connectors/BaseConnector.scala
app/connectors/MessageConnector.scala
test/data/TestXml.scala

MessageConnector wasn't sending the correct content type in the header so downstream was responding with 415 Unsupported Media Type.<br><br>The CC044A example in TestXml has also been updated to contain the correct date field as downstream was failing with BadRequest without it.

Specify correct content type in MessageConnector

---

.gitignore
.scalafmt.conf
app/connectors/ArrivalConnector.scala
app/connectors/ArrivalMessageConnector.scala
app/connectors/DepartureMessageConnector.scala
app/connectors/DeparturesConnector.scala
app/controllers/ArrivalMessagesController.scala
app/controllers/ArrivalMovementController.scala
app/controllers/DepartureMessagesController.scala
app/controllers/DeparturesController.scala
app/metrics/HasMetrics.scala
app/metrics/MetricsKeys.scala
it/connectors/WiremockSuite.scala
it/utils/TestMetrics.scala
test/controllers/ArrivalMessagesControllerSpec.scala
test/controllers/ArrivalMovementControllerSpec.scala
test/controllers/DepartureMessagesControllerSpec.scala
test/controllers/DeparturesControllerSpec.scala
test/metrics/HasMetricsSpec.scala
test/utils/TestMetrics.scala

Add metrics collection to the controllers and connectors in the API
I have used the convention of using the controller method name in our controllers, and in using `<movement type>-backend-<http method>` in the connectors.

CTDA-1281 Add metrics collection to controllers and connectors

---

resources/public/api/conf/1.0/application.raml

The prod configuration PRs for this endpoint were never merged and we are in a change freeze. This will not work in prod if it's deployed now.

CTDA-1600 Revert GET /box endpoint as the prod config can't be merged

---

app/connectors/PushPullNotificationConnector.scala
app/connectors/util/CustomHttpReader.scala
app/controllers/PushPullNotificationController.scala
app/controllers/actions/ValidateArrivalMessageAction.scala
app/controllers/actions/ValidateArrivalNotificationAction.scala
app/controllers/actions/ValidateDepartureDeclarationAction.scala
app/controllers/actions/ValidateDepartureMessageAction.scala
app/models/response/HateoasResponseBox.scala
app/services/XmlValidationService.scala
app/utils/JsonHelper.scala
app/utils/ResponseHelper.scala
it/connectors/PushPullNotificationConnectorSpec.scala
it/services/EnsureGuaranteeServiceIntegrationSpec.scala
it/utils/WiremockSuite.scala
test/connectors/BaseConnectorSpec.scala
test/controllers/PushPullNotificationControllerSpec.scala
test/models/response/HateoasResponseBoxSpec.scala
test/services/XmlValidationServiceSpec.scala
test/xml/CC007ASpec.scala
test/xml/CC014ASpec.scala
test/xml/CC015BSpec.scala
test/xml/CC044ASpec.scala

This is an alternative to #236 - if this is merged, that shouldn't be (and vice versa).
Still need to get data on which route to take, but wanted to show this could be done.
Scalafmt was run first, so you're most likely to be interested in the second commit for the actual changes.

CTDA-1861 Alternative: Reject messages with namespaces on root tag 

---

app/controllers/actions/ValidateArrivalMessageAction.scala
app/controllers/actions/ValidateArrivalNotificationAction.scala
app/controllers/actions/ValidateDepartureDeclarationAction.scala
app/controllers/actions/ValidateDepartureMessageAction.scala
app/services/XmlValidationService.scala
it/services/EnsureGuaranteeServiceIntegrationSpec.scala
test/services/XmlValidationServiceSpec.scala
test/xml/CC007ASpec.scala
test/xml/CC014ASpec.scala
test/xml/CC015BSpec.scala
test/xml/CC044ASpec.scala

This reverts commit 182e9bc0a9c7dde22686c2760fed729a1f3a7b76.
There were unforseen errors from traders that don't have namespaces on their XML files but have been hit by this check. Pending seeing some of these messages, we'll revert this commit so we don't impede developers.
This will need https://github.com/hmrc/common-transit-convention-traders-postman/commit/0f89d9cfdfc843c8ce9507e6211150f6a4357633 reverting too.

CLI-156: Revert "CTDA-1861: Reject messages with a namespace on the root node"

---

app/config/AppConfig.scala
app/controllers/actions/ValidateArrivalMessageAction.scala
app/controllers/actions/ValidateArrivalNotificationAction.scala
app/controllers/actions/ValidateDepartureDeclarationAction.scala
app/controllers/actions/ValidateDepartureMessageAction.scala
app/services/XmlValidationService.scala
conf/application.conf
it/services/EnsureGuaranteeServiceIntegrationSpec.scala
test/services/XmlValidationServiceSpec.scala
test/xml/CC007ASpec.scala
test/xml/CC014ASpec.scala
test/xml/CC015BSpec.scala
test/xml/CC044ASpec.scala

This reverts commit 9155c4702b998bcbda26ba3a945ea96529ed7899, but allowing explicitly null/empty namespaces.
This is the original commit for CTDA-1861 plus an additional allowance for the `xmlns=""` namespace (see the second commit).
Also added a config option `xml-validation.block-unknown-namespaces` that we can use to control this without otherwise touching the code.

CLI-156: Re-introduce defensive XML measures

---

app/controllers/DeparturesController.scala
app/routing/DeparturesRouter.scala
app/routing/VersionedRouting.scala
app/v2/controllers/V2DeparturesController.scala
app/v2/controllers/actions/AuthNewEnrolmentOnlyAction.scala
app/v2/controllers/actions/MessageSizeAction.scala
app/v2/controllers/stream/StreamingParsers.scala
conf/app.routes
test/controllers/DeparturesControllerSpec.scala
test/routing/DeparturesRouterSpec.scala
test/routing/VersionedRoutingSpec.scala
test/v2/controllers/V2DeparturesControllerSpec.scala
test/v2/controllers/actions/AuthNewEnrolmentOnlyActionSpec.scala
test/v2/controllers/actions/MessageSizeActionSpec.scala
test/v2/controllers/stream/StreamingParsersSpec.scala
test/v2/fakes/controllers/FakeV1DeparturesController.scala
test/v2/fakes/controllers/FakeV2DeparturesController.scala
test/v2/fakes/controllers/actions/FakeAuthNewEnrolmentOnlyAction.scala

**Depends on #251 and #256**
Once the above two PRs are merged, only the last commit will be relavant for this PR. This moves all v2 code into its own package and separates out the routing code into its own controller (`DepraturesRouter`).
This will enable writing the Validation connector in the correct place.
Will rebase once the two PRs above are merged (or fates otherwise decided)

CTCP-266: Move v2 code into v2 package and add departures router to separate routing from the v1 code

---

resources/public/api/conf/2.0/application.raml
resources/public/api/conf/2.0/docs/errors.md

_Note that this PR is a draft as it is awaiting merge of CTCP-266, #255._
Adds text to the API definition as follows:
* Clarifies that the code from any BadRequest error is important - though we only have `SCHEMA_VALIDATION` at the moment (could there be more?)
* Adds a section under Errors with the form of the error that is returned (do we want this here, or should this go elsewhere?)
* Adds a trait to the RAML to allow adding schema validation to other endpoints as they get written.

CTCP-271: Update API Definition

---

app/controllers/actions/AuthAction.scala
app/v2/controllers/actions/AuthNewEnrolmentOnlyAction.scala
app/v2/models/errors/ErrorCode.scala
app/v2/models/errors/PresentationError.scala
test/controllers/actions/AuthActionSpec.scala
test/v2/controllers/actions/AuthNewEnrolmentOnlyActionSpec.scala

Currently we are returning 500 from our service when the auth service returns an error response. The issue is that in the response, the reason for the failure is being captured and returned to the user. This PR logs the exception returned rather than including it in the internal server error response.

Return 500 in AuthAction when auth service returns an error response

---

app/routing/VersionedRouting.scala
test/routing/VersionedRoutingSpec.scala

If we directly invoke the action via a GET endpoint with a content type, Play correctly parses the body as empty. However, it seems when chaining the actions, Play will use the content type and try to parse an empty body. To sidestep this, we drain the request body (which should be empty anyway) and manually remove the content type so that the GET endpoints don't try to parse things as the content type suggests.

CTCP-773: Fix routing to V1 GET/DELETE endpoints when a content type is defined

---

app/models/Binders.scala
app/v2/models/responses/hateoas/HateoasResponse.scala
test/v2/connectors/V2BaseConnectorSpec.scala
test/v2/models/responses/hateoas/HateoasDepartureMessageIdsResponseSpec.scala

Caught this when writing a regression test.
The implict binding for `OffsetDateTime` didn't work when trying to get a URL from the reverse routing because the system was looking for an implicit `PathBindable[Option[OffsetDateTime]]` -- the one that was found was the standard one which doesn't format to the ISO date time.
We have to explicity provide an implicit thanks to Play's Macro expansions.
Test updated to reflect what we really wanted.

CTCP-832: Fix returned datetime in receivedSince parameter for the Message IDs response

---

app/v2/models/AuditType.scala
app/v2/models/request/MessageType.scala

This corrects the name for the IE170, and in turn, will not cause the auditing service to return a 400.

CTCP-1512: Fix incorrect name for IE170

---

resources/public/api/conf/2.0/application.raml

There is one thing I'm a little bothered about, which is that the response examples don't include the description. We get this (via the API definition preview RAML function):
With the switch to OAS this might not be a problem, but for now, given we're stuck with RAML, we need to consider if we're happy with this or not.
@fmcgrath I'm sure I could word things better!

CTCP-1523: Update API Definition for additional accept header value

---

resources/public/api/conf/2.0/application.raml

I noticed that the departure ID examples in V2 was in the old format - int vs hex, so I updated those. I also fixed the response in one of the requests which was not reflecting what we actually return.

Added Get a cached arrival by arrival id to API definition 

---

app/v2/connectors/PersistenceConnector.scala
app/v2/controllers/V2ArrivalsController.scala
app/v2/controllers/V2DeparturesController.scala
app/v2/services/ArrivalsService.scala
app/v2/services/DeparturesService.scala
it/v2/connectors/PersistenceConnectorSpec.scala
it/v2/utils/CommonGenerators.scala
test/v2/controllers/V2ArrivalsControllerSpec.scala
test/v2/controllers/V2DeparturesControllerSpec.scala
test/v2/services/ArrivalsServiceSpec.scala
test/v2/services/DeparturesServiceSpec.scala
test/v2/services/JsonMessageParsingServiceSpec.scala

This can be merged as all current scenarios will continue to work -- but the `updatedSince` parameter won't work until the respective PR on `transit-movements` is implemeneted.

CTCP-1682: Enable passthrough of updatedSince parameter for get movement by EORI endpoints

---

app/v2/controllers/ErrorTranslator.scala
app/v2/models/errors/ErrorCode.scala
app/v2/models/errors/PresentationError.scala
app/v2/models/errors/RouterError.scala
app/v2/services/RouterService.scala
test/v2/controllers/ErrorTranslatorSpec.scala
test/v2/controllers/V2DeparturesControllerSpec.scala
test/v2/services/RouterServiceSpec.scala

Router: https://github.com/hmrc/transit-movements-router/pull/26
Regression tests: https://github.com/hmrc/ctc-traders-api-tests/pull/65

CTCP-1665: Support enhanced error message for incorrect customs offices

---

resources/public/api/conf/2.0/application.yaml

The automated conversion from RAML to OAS left the OpenAPI specs in a bit of a weird state, but functional for our needs. However, this has caused us to miss a few things when updating the spec, and has caused duplication that didn't need to be there.
This clears that up. This also fixes a couple of examples to use multi-examples.

Remove redundancy from v2 OAS, fix examples, fix schema

---

app/config/AppConfig.scala
app/v2/connectors/UpscanConnector.scala
app/v2/controllers/V2MovementsController.scala
conf/app.routes
conf/application.conf
it/v2/connectors/UpscanConnectorSpec.scala
it/v2/utils/CommonGenerators.scala
test/v2/base/HeaderCarrierMatcher.scala
test/v2/base/TestCommonGenerators.scala
test/v2/controllers/V2MovementsControllerSpec.scala
test/v2/fakes/controllers/FakeV2MovementsController.scala
test/v2/services/UpscanServiceSpec.scala

On External Test, a message sent via Upscan is not getting through to ERMIS as the Upscan callback does not have the client ID. This corrects that by:
* Appending the client ID to the callback URL in the initiate call
* Reading the client ID from the callback method and adding it to the `HeaderCarrier`
Some tests have been modified to test this.

CTCP-3475: Add client ID to Upscan callback to enable it to pass through to the stub

---

project/plugins.sbt
resources/public/api/conf/2.0/application.yaml

Also update definition regarding the 8MB uplift.

CTCP-3737: Remove documentation regarding duplicate LRNs

---

app/v2/connectors/PersistenceConnector.scala
it/test/v2/connectors/PersistenceConnectorSpec.scala

Pass Optional clientId to transit-movements as part of Header for createDeparture and createArrival request. So that we can save clientId in transit-movements database.
Note:- for web clientId is optional and for API it is mandatory.

Add clientId in common-transit-convention-traders and pass to persistence service

---

app/routing/GenericRouting.scala
conf/app.routes
test/routing/GenericRoutingSpec.scala
test/v2/controllers/V2MovementsControllerSpec.scala
test/v2_1/controllers/V2MovementsControllerSpec.scala

During testing of the v2.1 routing it was noticed that one of the endpoints did not have the correct routing in place.

Added v2.1 routing to getMessageBody
